"""Add user_id to CameraSettings

Revision ID: 061cdbdc74d0
Revises: 984e489ece60
Create Date: 2025-05-31 21:29:45.573933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061cdbdc74d0'
down_revision = '984e489ece60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('contrast',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_camera_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('contrast',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
