"""Initial migration

Revision ID: bd718a99e76e
Revises: 
Create Date: 2025-05-29 18:02:26.989159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd718a99e76e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_settings', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
